SELECT index, "ID_REGISTRO", "PAIS_ORIGEN", "PAIS_NACIONALIDAD", "MIGRANTE", 
"HABLA_LENGUA_INDIG", "NACIONALIDAD", "EDAD", "MUNICIPIO_RES", "ENTIDAD_NAC", 
"SEXO", "SECTOR", "ORIGEN", "ABR_ENT", "ENTIDAD", "ENTIDAD_REGISTRO", "ENTIDAD_RES"
FROM public.pat_demographic;

SELECT index, "ID_REGISTRO", "RESULTADO", "DELAY", "TIPO_PACIENTE",
"FECHA_INGRESO", "FECHA_SINTOMAS", "ENTIDAD_UM", "INTUBADO", "UCI",
"FECHA_DEF"
FROM public.pat_hospitalization;

SELECT index, "ID_REGISTRO", "EMBARAZO", "NEUMONIA", "DIABETES", 
"EPOC", "ASMA", "INMUSUPR", "HIPERTENSION", "CARDIOVASCULAR", 
"OTRA_COM", "OBESIDAD", "RENAL_CRONICA", "TABAQUISMO", "OTRO_CASO"
	FROM public.pat_underlying;
	
SELECT "ID", "ID_REGISTRO", "FECHA_ARCHIVO", "FECHA_ACTUALIZACION"
FROM public.pat_miscellaneous;



